language: node_js
node_js:
  - 13
​
services:
  - docker
​
script:

  - docker build -t udagram-api-feed:v2a ./udagram-api-feed
  - docker build -t udagram-api-user:v2a ./udagram-api-user
  - docker build -t udagram-frontend:v2b ./udagram-frontend
  - docker build -t reverseproxy:v2a ./udagram-reverseproxy  


  - docker tag udagram-api-feed:v2a baovqq/api-feed:v2a
  - docker tag udagram-api-user:v2a baovqq/api-user:v2a
  - docker tag udagram-frontend:v2b baovqq/front-end:v2b
  - docker tag reverseproxy:v2a baovqq/reverseproxy:v2a

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push baovqq/reverseproxy:v2a
  - docker push baovqq/api-user:v2a
  - docker push baovqq/api-feed:v2a
  - docker push baovqq/front-end:v2b
