language: node_js
node_js:
  - 13
​
services:
  - docker
​
script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy baovqq/reverseproxy:latest
  - docker tag udagram-api-feed baovqq/api-feed:latest
  - docker tag udagram-api-user baovqq/api-user:latest
  - docker tag udagram-frontend baovqq/front-end:latest
​
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push baovqq/reverseproxy
  - docker push baovqq/api-user
  - docker push baovqq/api-feed
  - docker push baovqq/front-end
