language: node_js
node_js:
  - 13
​
services:
  - docker
​
script:

  - docker build -t feed:v6 ./udagram-api-feed
  #- docker build -t user:v5 ./udagram-api-user
  #- docker build -t frontend:v5 ./udagram-frontend
  #- docker build -t reverseproxy:v5 ./udagram-reverseproxy  

  - docker tag feed:v6 baovqq/feed:v6
  #- docker tag user:v5 baovqq/user:v5
  #- docker tag frontend:v5 baovqq/frontend:v5
  #- docker tag reverseproxy:v5 baovqq/reverseproxy:v5

after_success:
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- docker push baovqq/reverseproxy:v5
  #- docker push baovqq/user:v5
  - docker push baovqq/feed:v6
  #- docker push baovqq/frontend:v5