language: node_js
node_js:
  - 13
​
services:
  - docker
​
script:

  #- docker build -t udagram-api-feed:v3a ./udagram-api-feed
  #- docker build -t udagram-api-user:v3a ./udagram-api-user
  - docker build -t udagram-frontend:v3c ./udagram-frontend
  #- docker build -t reverseproxy:v3a ./udagram-reverseproxy  


  #- docker tag udagram-api-feed:v3a baovqq/api-feed:v3a
  #- docker tag udagram-api-user:v3a baovqq/api-user:v3a
  - docker tag udagram-frontend:v3c baovqq/front-end:v3c
  #- docker tag reverseproxy:v3a baovqq/reverseproxy:v3a

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- docker push baovqq/reverseproxy:v3a
  #- docker push baovqq/api-user:v3a
  #- docker push baovqq/api-feed:v3a
  - docker push baovqq/front-end:v3c
