language: node_js
node_js:
  - 13
​
services:
  - docker
​
script:

  #- docker build -t feed:v1 ./udagram-api-feed
  #- docker build -t user:v1 ./udagram-api-user
  - docker build -t frontend:v1a ./udagram-frontend
  #- docker build -t reverseproxy:v1 ./udagram-reverseproxy  

  #- docker tag feed:v1 baovqq/feed:v1
  #- docker tag user:v1 baovqq/user:v1
  - docker tag frontend:v1a baovqq/frontend:v1a
  #- docker tag reverseproxy:v1 baovqq/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- docker push baovqq/reverseproxy:v1
  #- docker push baovqq/user:v1
  #- docker push baovqq/feed:v1
  - docker push baovqq/frontend:v1a