language: node_js
node_js:
  - 13
​
services:
  - docker
​
script:

  #- docker build -t feed:v7 ./udagram-api-feed
  #- docker build -t user:v5 ./udagram-api-user
  - docker build -t frontend:v5a ./udagram-frontend
  #- docker build -t reverseproxy:v5 ./udagram-reverseproxy  

  #- docker tag feed:v7 baovqq/feed:v7
  #- docker tag user:v5 baovqq/user:v5
  - docker tag frontend:v5a baovqq/frontend:v5a
  #- docker tag reverseproxy:v5 baovqq/reverseproxy:v5

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- docker push baovqq/reverseproxy:v5
  #- docker push baovqq/user:v5
  #- docker push baovqq/feed:v7
  - docker push baovqq/frontend:v5a