version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v5
  backend-user:
    build:
      context: ./udagram-api-user
    image: user:v5
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: feed:v5
  frontend:
    build:
      context: ./udagram-frontend
    image: frontend:v5