apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: backend-user
  labels: 
    app: backend-user
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: backend-user
  template: 
    metadata: 
      labels: 
        app: backend-user
    spec: 
      containers: 
        - name: backend-user
          image: baovqq/api-user:v3a
          imagePullPolicy: Always
          resources:
            requests:            
              cpu: 250m
            limits:            
              cpu: 500m
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: config-secret
          ports: 
            - containerPort: 8080