apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - image: baovqq/api-user:v2
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            cpu: "250m"
          limits:            
            cpu: "500m"      
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: map-config
              key: URL 
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: map-config
              key: JWT_SECRET
        - name: POSTGRESS_DB
          valueFrom:
            configMapKeyRef:
              name: map-config
              key: POSTGRESS_DB
        - name: POSTGRESS_HOST
          valueFrom:
            configMapKeyRef:
              name: map-config
              key: POSTGRESS_HOST
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRESS_PASSWORD
        - name: POSTGRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRESS_USERNAME
      restartPolicy: Always


